omero render set: clarify help around settings for disabled channels
ome/omero-cli-render pull request #67
Opened 2024-11-15 08:47 UTC by sbesson

Closes #66

The underlying code change has been applied in #43 and released since `omero-cli-render 0.6.0` but the help was never updated and was still documenting the previous behavior.

2024-11-15 10:07 UTC, pwalczysko commented on src/omero_cli_render.py
> +    # All specified settings are applied to the given channel independently of
```suggestion
    # All specified settings are applied to the given channel, whether or not 
```

2024-11-15 10:09 UTC, pwalczysko commented on src/omero_cli_render.py
> +    # active is set and its value.
```suggestion
    # active parameter is set and whatever value it has.
```

2024-11-15 10:10 UTC, pwalczysko requested changes
Thank you @sbesson - please see some reformulation suggestions. To be fair, I did understand your formulation too.

2024-11-15 10:13 UTC, sbesson commented
Thanks @pwalczysko slightly reformulated the second sentence to make it more grammatically correct. Can you take another look?

2024-11-15 10:14 UTC, pwalczysko approved these changes
Yes, I cannot find a fault, both understanding and grammar seems +1 to me. Thanks

2024-11-21 14:00 UTC, jburel commented
```
flake8.main.application   MainProcess    623 INFO     Found a total of 12 violations and reported 1
./src/omero_cli_render.py:125:78: W291 trailing whitespace
```

2024-11-21 14:24 UTC, jburel approved these changes
Release as 0.8.2?

2024-11-21 14:29 UTC, sbesson commented
I think there is harm in releasing the package with the updated help message. Possibly depends on whether there are other candidates for inclusion.

2024-11-21 14:31 UTC, jburel commented
Nothing really in the pipeline as far as I can tell
cc @dominikl

2024-11-22 09:07 UTC, dominikl commented
Wonder if I could https://github.com/ome/omero-cli-render/pull/62 in as well? Probably have to merge this PR and then I can rebase my PR.

2024-11-22 09:13 UTC, dominikl approved these changes
👍

2024-11-27 09:43 UTC, merged